name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get version
      run: echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV 
#     run: echo ::set-env name=VERSION::$(git describe --tags)

    - name: Build
      run: |
        mkdir release

        tar --exclude="./release" -cvzf release/release.tar.gz . 

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
        files: release/release.tar.gz
