name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get version
      run: echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV 
#     run: echo ::set-env name=VERSION::$(git describe --tags)

    - name: Build
      run: |
        mkdir release
        tar --exclude="./release" -cvzf release/release.tar.gz . 
        mv release/release.tar.gz .

    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.VERSION }}
        prerelease: false
        title: "Production Build"
        files: |
          release.tar.gz  

